#!/usr/bin/env python3
"""Lift every captured SPURS job image and regenerate src/gen/spu_workloads.c.

SPURS job binaries are raw code+data blobs, not ELFs, and this title's are not
at a fixed address -- the runtime only sees one when the chain dispatches it.
Capture them first, then lift:

    SPU_DUMP_MISS=analysis/spu/dump ./build/gt5p.exe      # run until quiet
    python scripts/lift_spu_jobs.py

The dump filenames carry the fingerprint the runtime computed
(spujob_<FP>_<size>.bin), which is the value to register: that hash is seeded
with 1469598103934665603 -- the FNV-1a-64 offset basis with a digit dropped --
so anything computed offline with a real FNV-1a-64 will not match, and a
mismatch is silent (the job logs `dispatch MISS` and does nothing).

The WWS job manager policy module is different: it is embedded in EMAIN.ELF at
a known address, so its fingerprint is computed in-process instead of baked in.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT.parent / "ps3recomp" / "tools"
DUMPS = ROOT / "analysis" / "spu" / "dump"
OUT = ROOT / "generated" / "spu_lifted"
REG = ROOT / "src" / "gen" / "spu_workloads.c"

WWS_JOB_PM_EA = 0x00F4CB80
WWS_JOB_PM_SIZE = 11648

NAME_RE = re.compile(r"^spujob_([0-9A-Fa-f]{16})_(\d+)\.bin$")


def run(*args):
    r = subprocess.run([sys.executable, *map(str, args)],
                       capture_output=True, text=True, cwd=ROOT)
    if r.returncode:
        print(r.stdout[-2000:], r.stderr[-2000:], sep="\n", file=sys.stderr)
        raise SystemExit(f"failed: {' '.join(map(str, args))}")
    return r.stdout


def lift(blob, prefix, outdir):
    funcs = outdir.parent / f"{outdir.name}_funcs.json"
    out = run(TOOLS / "find_spu_functions.py", "--raw", "--base", "0",
              "--out", funcs, blob)
    n_funcs = re.search(r"Detected ([\d,]+) function", out)
    run(TOOLS / "spu_lifter.py", blob, "--base", "0", "--functions", funcs,
        "--symbol-prefix", prefix, "--output", outdir, "--source-name", "spu_recomp.c")
    return int(n_funcs.group(1).replace(",", "")) if n_funcs else 0


def main():
    dumps = sorted(p for p in DUMPS.glob("spujob_*.bin") if NAME_RE.match(p.name))
    if not dumps:
        raise SystemExit(f"no spujob_*.bin in {DUMPS} -- run with SPU_DUMP_MISS first")

    # image_id 1 is the policy module; jobs take 2..N.
    jobs, total = [], 0
    for i, blob in enumerate(dumps, start=2):
        fp, size = NAME_RE.match(blob.name).groups()
        prefix = f"gt5p_j{fp[:8]}"
        outdir = OUT / f"j{fp[:8]}"
        outdir.mkdir(parents=True, exist_ok=True)
        n = lift(blob, prefix, outdir)
        total += n
        print(f"  {blob.name}: {n} functions -> {outdir.relative_to(ROOT)}")
        jobs.append((fp, int(size), prefix, i, blob.name))

    externs = "\n".join(
        f"extern void {p}_spu_func_00000000(spu_context*);\n"
        f"extern void {p}_spu_recomp_register(void);" for _, _, p, _, _ in jobs)
    regs = "\n\n".join(
        f"    /* {name} */\n"
        f"    spu_begin_image({img});\n"
        f"    {p}_spu_recomp_register();\n"
        f"    spu_workload_register_img(0x{fp}ULL, {p}_spu_func_00000000, {img},\n"
        f"                              \"j{fp[:8]}\");"
        for fp, _sz, p, img, name in jobs)

    REG.write_text(TEMPLATE.format(externs=externs, regs=regs,
                                   pm_ea=f"0x{WWS_JOB_PM_EA:08X}",
                                   pm_size=WWS_JOB_PM_SIZE,
                                   n_jobs=len(jobs)), encoding="utf-8")
    print(f"\n{len(jobs)} job images, {total} SPU functions lifted")
    print(f"wrote {REG.relative_to(ROOT)}")


TEMPLATE = '''/* SPU workload registry for Gran Turismo 5 Prologue -- GENERATED by
 * scripts/lift_spu_jobs.py. Do not edit by hand.
 *
 * The runtime matches a guest SPU image by content fingerprint and runs the
 * lifted entry registered here. Without a match it logs
 *
 *     [spurs-job] dispatch MISS fp=... size=... job=...
 *
 * and runs nothing, silently -- the job does no work and whatever was waiting
 * on it waits forever.
 *
 * Two kinds of image are registered below.
 *
 * The WWS job manager POLICY MODULE is embedded in EMAIN.ELF at a known
 * address, so its fingerprint is computed here from the loaded image using the
 * runtime's own hash. That is not fussiness: spu_workload_fingerprint is
 * documented as FNV-1a-64 but seeds with 1469598103934665603, the offset basis
 * with a digit dropped (14695981039346656037 is the real one). Self-consistent,
 * so it hashes fine -- but a constant from any offline FNV-1a-64 will not match.
 *
 * The JOB images have no fixed address; they are only visible when the chain
 * dispatches them. Their fingerprints come from the SPU_DUMP_MISS filenames,
 * which is the runtime's own value, so they are safe to bake in. A fingerprint
 * here must match its dumped file exactly or the image will miss again.
 */
#include <stdio.h>
#include <stdint.h>
#include "spu_workload.h"

extern unsigned char* vm_base;
extern void spu_begin_image(int image_id);

extern void gt5p_wwsjob_spu_func_00000000(spu_context*);
extern void gt5p_wwsjob_spu_recomp_register(void);

{externs}

#define WWS_JOB_PM_EA   {pm_ea}u
#define WWS_JOB_PM_SIZE {pm_size}u

/* Call after the ELF is in memory and before the game creates any SPURS
 * workload, job chain or task -- main.cpp does both. */
void gt5p_spu_register_all(void)
{{
    uint64_t fp = spu_workload_fingerprint(vm_base + WWS_JOB_PM_EA, WWS_JOB_PM_SIZE);

    spu_begin_image(1);
    gt5p_wwsjob_spu_recomp_register();
    spu_workload_register_img(fp, gt5p_wwsjob_spu_func_00000000, 1, "Wws_Job");

{regs}

    spu_begin_image(0);

    printf("[GT5P] SPU: Wws_Job (fp=0x%016llX) + {n_jobs} job image(s) registered\\n",
           (unsigned long long)fp);
}}
'''

if __name__ == "__main__":
    main()
